name: Release version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Release version
      run: |
        cd applicant
        ls -la
        chmod +x gradlew
        ./gradlew build
        ./gradlew assembleRelease

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 343.0.0
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - name: Generate Signed URL
      id: signed-url
      run: |
        SIGNED_URL=$(gsutil signurl -d 10m $GCLOUD_BUCKET_URL)
        echo "::set-output name=signed_url::${SIGNED_URL}"
      env:
        GCLOUD_BUCKET_URL: "gs://your-bucket-name/path/to/apk.apk"
    - name: Upload APK to GCS
      run: |
        curl -X PUT -T app/build/outputs/apk/release/app-release.apk "${{ steps.signed-url.outputs.signed_url }}"
      env:
        GCS_APK_PATH: "gs://your-bucket-name/path/to/apk.apk"
      working-directory: app/build/outputs/apk/release

  
    
