name: Release version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Obtener versión desde build.gradle
        id: get-version
        run: echo "::set-output name=version::$(cat app/build.gradle | grep "versionCode" | grep -o '[0-9]\+')"

      - name: Crear Rama de Lanzamiento
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          RELEASE_BRANCH=release/v$VERSION
          
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH

      - name: Finalizar Flujo de Trabajo
        run: echo "Rama de lanzamiento creada y actualizada."
    
